### ISSUE TITLE
Alarm Sound appears to be disconnected

### ISSUE THREAD

**Issue by jopinto** [potomak/tomatoes#134] opened 2015-06-24 04:45 UTC
Hi, guys

I have been using the application for quite some time now but recentely noticed (probably over the last few days) that the alarm sound appears to be disconnected, therefore there is no way for me to know when the pomodoro is finished. I even tried to check if it was me by increasing the overall volume level on my equipment, and also enabling the ticking sound on the application, but none of this made the trick.

I thought you might want to know. I miss the reminder when a pomodoro is finished and it's time to take a break :-D

**Comment by epatarroyo** [comment] 2015-06-24 05:06
Sound works for me, I think the problem is related with your
browser/computer

Have you tried with another browser/computer?

**Comment by jopinto** [comment] 2015-06-24 05:37
Let me check on that then. Will get back to you with a response.





Joel J. Pinto
Móvil 671 664 845
Email jopinto1009@yahoo.com
Web www.joelpintoromero.com

**Comment by jopinto** [comment] 2015-06-24 05:46
You are right. I did try it on Explorer and Firefox and works fine. What do you recommend me to do? Unistall / reinstall Chrome?




     Joel Pinto Romero - Consultor Comercial Independiente
      Móvil (+34) 671 664 845
      Email:joel@joelpintoromero.com
      Twitter: @JoelPintoRomero
      www.joelpintoromero.com

**Comment by jopinto** [comment] 2015-06-24 06:07
Hi, Ernesto

I did unistall and reinstall Chrome and the problem persists, even though I know (and acknowledge) I did try the application on other browsers and it worked fine. What could the problem be?




     Joel Pinto Romero - Consultor Comercial Independiente
      Móvil (+34) 671 664 845
      Email:joel@joelpintoromero.com
      Twitter: @JoelPintoRomero
      www.joelpintoromero.com

**Comment by potomak** [comment] 2015-06-24 14:16
@jopinto try to open inspector's console to see if there are any errors. You could also try to open tomatoes in an incognito window. If you have extensions I'd suggest also to try to disable them to see if there's an incompatibility between Tomatoes and one of them.

A workaround in the meantime would be to enable desktop notifications. To do so go to your profile and click on the link at the top of the page to enable them.

**Comment by jopinto** [comment] 2015-06-24 14:22
Thanks a lot,

I was able to sort it out by uninstalling and reinstalling the Chrome extension for tomato.es

Cheers





Joel J. Pinto
Móvil 671 664 845
Email jopinto1009@yahoo.com
Web www.joelpintoromero.com

**Comment by potomak** [comment] 2015-06-24 14:48
Ok, I'm closing this issue.

**Closed by potomak** 2015-06-24 14:48 UTC

**Comment by jopinto** [comment] 2015-06-24 14:53
Sure. Will let you know if it comes alive again.

Thanks buddy 





Joel J. Pinto
Móvil 671 664 845
Email jopinto1009@yahoo.com
Web www.joelpintoromero.com
