### ISSUE TITLE
Statistic pages give an application error

### ISSUE THREAD

**Issue by vkaracic** [potomak/tomatoes#135] opened 2015-08-18 14:06 UTC
All the statics pages return an application error:
<img width="1235" alt="screen shot 2015-08-18 at 4 04 59 pm" src="https://cloud.githubusercontent.com/assets/2808092/9332046/0963a9ea-45c3-11e5-8cbb-9e34eb13762b.png">

**Comment by potomak** [comment] 2015-08-18 14:29
@vkaracic I can't reproduce the error on the [Statistics](http://www.tomato.es/statistics) page, but I get this error trying to access the Leaderboards pages, example: http://www.tomato.es/rankings?time_period=today.

**Comment by vkaracic** [comment] 2015-08-18 16:26
That's what I meant by "statistics", all the leaderboards pages return that error, not the statistic pages. Sorry about the confusion.

**Comment by potomak** [comment] 2016-11-30 06:18
Closed in favor of https://github.com/potomak/tomatoes/issues/206.

**Closed by potomak** 2016-11-30 06:18 UTC
Labels: bug
