### ISSUE TITLE
All Leaderboards links fail

### ISSUE THREAD

**Issue by mangeshdeshmukh** [potomak/tomatoes#139] opened 2016-05-16 05:26 UTC
All of the the below links fail with some error
http://www.tomato.es/rankings?time_period=this_week
http://www.tomato.es/rankings?time_period=this_month

**Comment by potomak** [comment] 2016-05-16 17:56
Yes, it's a know issue. These pages run queries that last longer than the default 60 secs timeout threshold.

Duplicate of https://github.com/potomak/tomatoes/issues/135.

**Closed by potomak** 2016-05-16 17:56 UTC
